/*  2026 북중미 월드컵 실제 데이터
 *  기준 시각: 2026-07-06 (조별리그 종료 / 32강 종료 / 16강 진행 중 / 8강 이후 미개최)
 *  출처: 위키피디아 각 조·녹아웃 페이지, ESPN, FIFA, NBC/CBS Sports, Sky Sports 등 교차 확인.
 *  ※ 8강~결승은 아직 열리지 않아 "미정"으로 둡니다. API 자동 업데이트가 이후 채웁니다.
 */
window.WC_DATA = {
  updatedAt: "2026-07-06T16:42:12+09:00",

  groups: [
    { name:"A",
      standings:[
        {rank:1, team:"멕시코",   played:3, won:3, drawn:0, lost:0, gf:6, ga:0, gd:6,  points:9},
        {rank:2, team:"남아프리카공화국", played:3, won:1, drawn:1, lost:1, gf:2, ga:3, gd:-1, points:4},
        {rank:3, team:"대한민국", played:3, won:1, drawn:0, lost:2, gf:2, ga:3, gd:-1, points:3},
        {rank:4, team:"체코",     played:3, won:0, drawn:1, lost:2, gf:2, ga:6, gd:-4, points:1}
      ],
      matches:[
        {date:"06-11", home:"멕시코", away:"남아프리카공화국", homeScore:2, awayScore:0, status:"FT",
          goals:[{minute:9,player:"Julián Quiñones",side:"home",type:"goal"},
                 {minute:67,player:"Raúl Jiménez",side:"home",type:"goal"}]},
        {date:"06-11", home:"대한민국", away:"체코", homeScore:2, awayScore:1, status:"FT",
          goals:[{minute:59,player:"Ladislav Krejčí",side:"away",type:"goal"},
                 {minute:67,player:"황인범",side:"home",type:"goal"},
                 {minute:80,player:"오현규",side:"home",type:"goal"}]},
        {date:"06-18", home:"체코", away:"남아프리카공화국", homeScore:1, awayScore:1, status:"FT",
          goals:[{minute:6,player:"Michal Sadílek",side:"home",type:"goal"},
                 {minute:83,player:"Teboho Mokoena",side:"away",type:"penalty"}]},
        {date:"06-18", home:"멕시코", away:"대한민국", homeScore:1, awayScore:0, status:"FT",
          goals:[{minute:50,player:"Luis Romo",side:"home",type:"goal"}]},
        {date:"06-24", home:"체코", away:"멕시코", homeScore:0, awayScore:3, status:"FT",
          goals:[{minute:55,player:"Mateo Chávez",side:"away",type:"goal"},
                 {minute:61,player:"Julián Quiñones",side:"away",type:"goal"},
                 {minute:"90+4",player:"Álvaro Fidalgo",side:"away",type:"goal"}]},
        {date:"06-24", home:"남아프리카공화국", away:"대한민국", homeScore:1, awayScore:0, status:"FT",
          goals:[{minute:63,player:"Thapelo Maseko",side:"home",type:"goal"}]}
      ]},

    { name:"B",
      standings:[
        {rank:1, team:"스위스", played:3, won:2, drawn:1, lost:0, gf:7, ga:3, gd:4,  points:7},
        {rank:2, team:"캐나다", played:3, won:1, drawn:1, lost:1, gf:8, ga:3, gd:5,  points:4},
        {rank:3, team:"보스니아헤르체고비나", played:3, won:1, drawn:1, lost:1, gf:5, ga:6, gd:-1, points:4},
        {rank:4, team:"카타르", played:3, won:0, drawn:1, lost:2, gf:2, ga:10, gd:-8, points:1}
      ],
      matches:[
        {date:"06-12", home:"캐나다", away:"보스니아헤르체고비나", homeScore:1, awayScore:1, status:"FT",
          goals:[{minute:21,player:"Jovo Lukić",side:"away",type:"goal"},
                 {minute:78,player:"Cyle Larin",side:"home",type:"goal"}]},
        {date:"06-13", home:"카타르", away:"스위스", homeScore:1, awayScore:1, status:"FT",
          goals:[{minute:17,player:"Breel Embolo",side:"away",type:"penalty"},
                 {minute:"90+4",player:"Miro Muheim",side:"home",type:"own"}]},
        {date:"06-18", home:"스위스", away:"보스니아헤르체고비나", homeScore:4, awayScore:1, status:"FT",
          goals:[{minute:74,player:"Johan Manzambi",side:"home",type:"goal"},
                 {minute:84,player:"Rubén Vargas",side:"home",type:"goal"},
                 {minute:90,player:"Johan Manzambi",side:"home",type:"goal"},
                 {minute:"90+3",player:"Ermin Mahmić",side:"away",type:"goal"},
                 {minute:"90+7",player:"Granit Xhaka",side:"home",type:"penalty"}]},
        {date:"06-18", home:"캐나다", away:"카타르", homeScore:6, awayScore:0, status:"FT",
          goals:[{minute:16,player:"Cyle Larin",side:"home",type:"goal"},
                 {minute:29,player:"Jonathan David",side:"home",type:"goal"},
                 {minute:"45+3",player:"Jonathan David",side:"home",type:"goal"},
                 {minute:64,player:"Nathan Saliba",side:"home",type:"goal"},
                 {minute:75,player:"Mohamed Manai",side:"home",type:"own"},
                 {minute:"90+2",player:"Jonathan David",side:"home",type:"goal"}]},
        {date:"06-24", home:"스위스", away:"캐나다", homeScore:2, awayScore:1, status:"FT",
          goals:[{minute:46,player:"Rubén Vargas",side:"home",type:"goal"},
                 {minute:57,player:"Johan Manzambi",side:"home",type:"goal"},
                 {minute:76,player:"Promise David",side:"away",type:"goal"}]},
        {date:"06-24", home:"보스니아헤르체고비나", away:"카타르", homeScore:3, awayScore:1, status:"FT",
          goals:[{minute:29,player:"Kerim Alajbegović",side:"home",type:"goal"},
                 {minute:34,player:"Mahmud Abunada",side:"home",type:"own"},
                 {minute:42,player:"Hassan Al-Haydos",side:"away",type:"goal"},
                 {minute:80,player:"Ermin Mahmić",side:"home",type:"goal"}]}
      ]},

    { name:"C",
      standings:[
        {rank:1, team:"브라질", played:3, won:2, drawn:1, lost:0, gf:7, ga:1, gd:6,  points:7},
        {rank:2, team:"모로코", played:3, won:2, drawn:1, lost:0, gf:6, ga:3, gd:3,  points:7},
        {rank:3, team:"스코틀랜드", played:3, won:1, drawn:0, lost:2, gf:1, ga:4, gd:-3, points:3},
        {rank:4, team:"아이티", played:3, won:0, drawn:0, lost:3, gf:2, ga:8, gd:-6, points:0}
      ],
      matches:[
        {date:"06-13", home:"브라질", away:"모로코", homeScore:1, awayScore:1, status:"FT",
          goals:[{minute:21,player:"Ismael Saibari",side:"away",type:"goal"},
                 {minute:32,player:"Vinícius Júnior",side:"home",type:"goal"}]},
        {date:"06-13", home:"아이티", away:"스코틀랜드", homeScore:0, awayScore:1, status:"FT",
          goals:[{minute:28,player:"John McGinn",side:"away",type:"goal"}]},
        {date:"06-19", home:"스코틀랜드", away:"모로코", homeScore:0, awayScore:1, status:"FT",
          goals:[{minute:2,player:"Ismael Saibari",side:"away",type:"goal"}]},
        {date:"06-19", home:"브라질", away:"아이티", homeScore:3, awayScore:0, status:"FT",
          goals:[{minute:23,player:"Matheus Cunha",side:"home",type:"goal"},
                 {minute:36,player:"Matheus Cunha",side:"home",type:"goal"},
                 {minute:"45+3",player:"Vinícius Júnior",side:"home",type:"goal"}]},
        {date:"06-24", home:"스코틀랜드", away:"브라질", homeScore:0, awayScore:3, status:"FT",
          goals:[{minute:7,player:"Vinícius Júnior",side:"away",type:"goal"},
                 {minute:"45+3",player:"Vinícius Júnior",side:"away",type:"goal"},
                 {minute:60,player:"Matheus Cunha",side:"away",type:"goal"}]},
        {date:"06-24", home:"모로코", away:"아이티", homeScore:4, awayScore:2, status:"FT",
          goals:[{minute:10,player:"Yassine Bounou",side:"away",type:"own"},
                 {minute:39,player:"Achraf Hakimi",side:"home",type:"goal"},
                 {minute:43,player:"Wilson Isidor",side:"away",type:"goal"},
                 {minute:"45+1",player:"Ismael Saibari",side:"home",type:"goal"},
                 {minute:78,player:"Soufiane Rahimi",side:"home",type:"goal"},
                 {minute:89,player:"Gessime Yassine",side:"home",type:"goal"}]}
      ]},

    { name:"D",
      standings:[
        {rank:1, team:"미국",   played:3, won:2, drawn:0, lost:1, gf:8, ga:4, gd:4,  points:6},
        {rank:2, team:"호주",   played:3, won:1, drawn:1, lost:1, gf:2, ga:2, gd:0,  points:4},
        {rank:3, team:"파라과이", played:3, won:1, drawn:1, lost:1, gf:2, ga:4, gd:-2, points:4},
        {rank:4, team:"튀르키예", played:3, won:1, drawn:0, lost:2, gf:3, ga:5, gd:-2, points:3}
      ],
      matches:[
        {date:"06-12", home:"미국", away:"파라과이", homeScore:4, awayScore:1, status:"FT",
          goals:[{minute:7,player:"Damián Bobadilla",side:"home",type:"own"},
                 {minute:31,player:"Folarin Balogun",side:"home",type:"goal"},
                 {minute:"45+5",player:"Folarin Balogun",side:"home",type:"goal"},
                 {minute:73,player:"Maurício",side:"away",type:"goal"},
                 {minute:"90+8",player:"Giovanni Reyna",side:"home",type:"goal"}]},
        {date:"06-13", home:"호주", away:"튀르키예", homeScore:2, awayScore:0, status:"FT",
          goals:[{minute:27,player:"Nestory Irankunda",side:"home",type:"goal"},
                 {minute:75,player:"Connor Metcalfe",side:"home",type:"goal"}]},
        {date:"06-19", home:"미국", away:"호주", homeScore:2, awayScore:0, status:"FT",
          goals:[{minute:11,player:"Cameron Burgess",side:"home",type:"own"},
                 {minute:43,player:"Alex Freeman",side:"home",type:"goal"}]},
        {date:"06-19", home:"튀르키예", away:"파라과이", homeScore:0, awayScore:1, status:"FT",
          goals:[{minute:2,player:"Matías Galarza",side:"away",type:"goal"}]},
        {date:"06-25", home:"튀르키예", away:"미국", homeScore:3, awayScore:2, status:"FT",
          goals:[{minute:3,player:"Auston Trusty",side:"away",type:"goal"},
                 {minute:10,player:"Arda Güler",side:"home",type:"goal"},
                 {minute:31,player:"Barış Alper Yılmaz",side:"home",type:"goal"},
                 {minute:49,player:"Sebastian Berhalter",side:"away",type:"goal"},
                 {minute:"90+8",player:"Kaan Ayhan",side:"home",type:"goal"}]},
        {date:"06-25", home:"파라과이", away:"호주", homeScore:0, awayScore:0, status:"FT", goals:[]}
      ]},

    { name:"E",
      standings:[
        {rank:1, team:"독일",   played:3, won:2, drawn:0, lost:1, gf:10, ga:4, gd:6,  points:6},
        {rank:2, team:"코트디부아르", played:3, won:2, drawn:0, lost:1, gf:4, ga:2, gd:2,  points:6},
        {rank:3, team:"에콰도르", played:3, won:1, drawn:1, lost:1, gf:2, ga:2, gd:0,  points:4},
        {rank:4, team:"쿠라소", played:3, won:0, drawn:1, lost:2, gf:1, ga:9, gd:-8, points:1}
      ],
      matches:[
        {date:"06-14", home:"독일", away:"쿠라소", homeScore:7, awayScore:1, status:"FT",
          goals:[{minute:6,player:"Felix Nmecha",side:"home",type:"goal"},
                 {minute:21,player:"Livano Comenencia",side:"away",type:"goal"},
                 {minute:38,player:"Nico Schlotterbeck",side:"home",type:"goal"},
                 {minute:"45+5",player:"Kai Havertz",side:"home",type:"penalty"},
                 {minute:47,player:"Jamal Musiala",side:"home",type:"goal"},
                 {minute:68,player:"Nathaniel Brown",side:"home",type:"goal"},
                 {minute:78,player:"Deniz Undav",side:"home",type:"goal"},
                 {minute:88,player:"Kai Havertz",side:"home",type:"goal"}]},
        {date:"06-14", home:"코트디부아르", away:"에콰도르", homeScore:1, awayScore:0, status:"FT",
          goals:[{minute:90,player:"Amad Diallo",side:"home",type:"goal"}]},
        {date:"06-20", home:"독일", away:"코트디부아르", homeScore:2, awayScore:1, status:"FT",
          goals:[{minute:30,player:"Franck Kessié",side:"away",type:"goal"},
                 {minute:68,player:"Deniz Undav",side:"home",type:"goal"},
                 {minute:"90+4",player:"Deniz Undav",side:"home",type:"goal"}]},
        {date:"06-20", home:"에콰도르", away:"쿠라소", homeScore:0, awayScore:0, status:"FT", goals:[]},
        {date:"06-25", home:"쿠라소", away:"코트디부아르", homeScore:0, awayScore:2, status:"FT",
          goals:[{minute:7,player:"Nicolas Pépé",side:"away",type:"goal"},
                 {minute:64,player:"Nicolas Pépé",side:"away",type:"goal"}]},
        {date:"06-25", home:"에콰도르", away:"독일", homeScore:2, awayScore:1, status:"FT",
          goals:[{minute:2,player:"Leroy Sané",side:"away",type:"goal"},
                 {minute:9,player:"Nilson Angulo",side:"home",type:"goal"},
                 {minute:77,player:"Gonzalo Plata",side:"home",type:"goal"}]}
      ]},

    { name:"F",
      standings:[
        {rank:1, team:"네덜란드", played:3, won:2, drawn:1, lost:0, gf:10, ga:4, gd:6,  points:7},
        {rank:2, team:"일본",   played:3, won:1, drawn:2, lost:0, gf:7, ga:3, gd:4,  points:5},
        {rank:3, team:"스웨덴", played:3, won:1, drawn:1, lost:1, gf:7, ga:7, gd:0,  points:4},
        {rank:4, team:"튀니지", played:3, won:0, drawn:0, lost:3, gf:2, ga:12, gd:-10, points:0}
      ],
      matches:[
        {date:"06-14", home:"네덜란드", away:"일본", homeScore:2, awayScore:2, status:"FT",
          goals:[{minute:51,player:"Virgil van Dijk",side:"home",type:"goal"},
                 {minute:57,player:"Keito Nakamura",side:"away",type:"goal"},
                 {minute:64,player:"Crysencio Summerville",side:"home",type:"goal"},
                 {minute:88,player:"Daichi Kamada",side:"away",type:"goal"}]},
        {date:"06-14", home:"스웨덴", away:"튀니지", homeScore:5, awayScore:1, status:"FT",
          goals:[{minute:7,player:"Yasin Ayari",side:"home",type:"goal"},
                 {minute:30,player:"Alexander Isak",side:"home",type:"goal"},
                 {minute:43,player:"Karim Rekik",side:"away",type:"goal"},
                 {minute:59,player:"Viktor Gyökeres",side:"home",type:"goal"},
                 {minute:84,player:"Mattias Svanberg",side:"home",type:"goal"},
                 {minute:"90+6",player:"Yasin Ayari",side:"home",type:"goal"}]},
        {date:"06-20", home:"네덜란드", away:"스웨덴", homeScore:5, awayScore:1, status:"FT",
          goals:[{minute:5,player:"Brian Brobbey",side:"home",type:"goal"},
                 {minute:17,player:"Brian Brobbey",side:"home",type:"goal"},
                 {minute:47,player:"Cody Gakpo",side:"home",type:"goal"},
                 {minute:54,player:"Cody Gakpo",side:"home",type:"goal"},
                 {minute:59,player:"Anthony Elanga",side:"away",type:"goal"},
                 {minute:89,player:"Crysencio Summerville",side:"home",type:"goal"}]},
        {date:"06-20", home:"튀니지", away:"일본", homeScore:0, awayScore:4, status:"FT",
          goals:[{minute:4,player:"Daichi Kamada",side:"away",type:"goal"},
                 {minute:31,player:"Ayase Ueda",side:"away",type:"goal"},
                 {minute:69,player:"Junya Ito",side:"away",type:"goal"},
                 {minute:83,player:"Ayase Ueda",side:"away",type:"goal"}]},
        {date:"06-25", home:"일본", away:"스웨덴", homeScore:1, awayScore:1, status:"FT",
          goals:[{minute:56,player:"Daizen Maeda",side:"home",type:"goal"},
                 {minute:62,player:"Anthony Elanga",side:"away",type:"goal"}]},
        {date:"06-25", home:"튀니지", away:"네덜란드", homeScore:1, awayScore:3, status:"FT",
          goals:[{minute:3,player:"Ellyes Skhiri",side:"away",type:"own"},
                 {minute:7,player:"Brian Brobbey",side:"away",type:"goal"},
                 {minute:54,player:"Hamza Mastouri",side:"home",type:"goal"},
                 {minute:62,player:"Mike van Hecke",side:"away",type:"goal"}]}
      ]},

    { name:"G",
      standings:[
        {rank:1, team:"벨기에", played:3, won:1, drawn:2, lost:0, gf:6, ga:2, gd:4,  points:5},
        {rank:2, team:"이집트", played:3, won:1, drawn:2, lost:0, gf:5, ga:3, gd:2,  points:5},
        {rank:3, team:"이란",   played:3, won:0, drawn:3, lost:0, gf:3, ga:3, gd:0,  points:3},
        {rank:4, team:"뉴질랜드", played:3, won:0, drawn:1, lost:2, gf:4, ga:10, gd:-6, points:1}
      ],
      matches:[
        {date:"06-15", home:"벨기에", away:"이집트", homeScore:1, awayScore:1, status:"FT",
          goals:[{minute:19,player:"Emam Ashour",side:"away",type:"goal"},
                 {minute:66,player:"Mohamed Hany",side:"away",type:"own"}]},
        {date:"06-15", home:"이란", away:"뉴질랜드", homeScore:2, awayScore:2, status:"FT",
          goals:[{minute:7,player:"Elijah Just",side:"away",type:"goal"},
                 {minute:32,player:"Ramin Rezaeian",side:"home",type:"goal"},
                 {minute:54,player:"Elijah Just",side:"away",type:"goal"},
                 {minute:64,player:"Mohammad Mohebi",side:"home",type:"goal"}]},
        {date:"06-21", home:"벨기에", away:"이란", homeScore:0, awayScore:0, status:"FT", goals:[]},
        {date:"06-21", home:"뉴질랜드", away:"이집트", homeScore:1, awayScore:3, status:"FT",
          goals:[{minute:15,player:"Finn Surman",side:"home",type:"goal"},
                 {minute:58,player:"Mostafa Ziko",side:"away",type:"goal"},
                 {minute:67,player:"Mohamed Salah",side:"away",type:"goal"},
                 {minute:82,player:"Trézéguet",side:"away",type:"goal"}]},
        {date:"06-26", home:"이집트", away:"이란", homeScore:1, awayScore:1, status:"FT",
          goals:[{minute:5,player:"Mahmoud Saber",side:"home",type:"goal"},
                 {minute:14,player:"Ramin Rezaeian",side:"away",type:"goal"}]},
        {date:"06-26", home:"뉴질랜드", away:"벨기에", homeScore:1, awayScore:5, status:"FT",
          goals:[{minute:28,player:"Leandro Trossard",side:"away",type:"goal"},
                 {minute:50,player:"Leandro Trossard",side:"away",type:"goal"},
                 {minute:66,player:"Kevin De Bruyne",side:"away",type:"goal"},
                 {minute:84,player:"Elijah Just",side:"home",type:"goal"},
                 {minute:86,player:"Romelu Lukaku",side:"away",type:"goal"},
                 {minute:"90+4",player:"Alexis Saelemaekers",side:"away",type:"goal"}]}
      ]},

    { name:"H",
      standings:[
        {rank:1, team:"스페인", played:3, won:2, drawn:1, lost:0, gf:5, ga:0, gd:5,  points:7},
        {rank:2, team:"카보베르데", played:3, won:0, drawn:3, lost:0, gf:2, ga:2, gd:0,  points:3},
        {rank:3, team:"우루과이", played:3, won:0, drawn:2, lost:1, gf:3, ga:4, gd:-1, points:2},
        {rank:4, team:"사우디아라비아", played:3, won:0, drawn:2, lost:1, gf:1, ga:5, gd:-4, points:2}
      ],
      matches:[
        {date:"06-15", home:"스페인", away:"카보베르데", homeScore:0, awayScore:0, status:"FT", goals:[]},
        {date:"06-15", home:"사우디아라비아", away:"우루과이", homeScore:1, awayScore:1, status:"FT",
          goals:[{minute:41,player:"Al-Amri",side:"home",type:"goal"},
                 {minute:80,player:"M. Araújo",side:"away",type:"goal"}]},
        {date:"06-21", home:"스페인", away:"사우디아라비아", homeScore:4, awayScore:0, status:"FT",
          goals:[{minute:10,player:"Lamine Yamal",side:"home",type:"goal"},
                 {minute:21,player:"Oyarzabal",side:"home",type:"goal"},
                 {minute:24,player:"Oyarzabal",side:"home",type:"goal"},
                 {minute:49,player:"Al-Tambakti",side:"home",type:"own"}]},
        {date:"06-21", home:"우루과이", away:"카보베르데", homeScore:2, awayScore:2, status:"FT",
          goals:[{minute:21,player:"K. Pina",side:"away",type:"goal"},
                 {minute:44,player:"M. Araújo",side:"home",type:"goal"},
                 {minute:"45+6",player:"Canobbio",side:"home",type:"goal"},
                 {minute:61,player:"Varela",side:"away",type:"goal"}]},
        {date:"06-26", home:"카보베르데", away:"사우디아라비아", homeScore:0, awayScore:0, status:"FT", goals:[]},
        {date:"06-26", home:"우루과이", away:"스페인", homeScore:0, awayScore:1, status:"FT",
          goals:[{minute:42,player:"Álex Baena",side:"away",type:"goal"}]}
      ]},

    { name:"I",
      standings:[
        {rank:1, team:"프랑스", played:3, won:3, drawn:0, lost:0, gf:10, ga:2, gd:8,  points:9},
        {rank:2, team:"노르웨이", played:3, won:2, drawn:0, lost:1, gf:8, ga:7, gd:1,  points:6},
        {rank:3, team:"세네갈", played:3, won:1, drawn:0, lost:2, gf:8, ga:6, gd:2,  points:3},
        {rank:4, team:"이라크", played:3, won:0, drawn:0, lost:3, gf:1, ga:12, gd:-11, points:0}
      ],
      matches:[
        {date:"06-16", home:"프랑스", away:"세네갈", homeScore:3, awayScore:1, status:"FT",
          goals:[{minute:66,player:"Kylian Mbappé",side:"home",type:"goal"},
                 {minute:82,player:"Bradley Barcola",side:"home",type:"goal"},
                 {minute:"90+5",player:"Ibrahim Mbaye",side:"away",type:"goal"},
                 {minute:"90+6",player:"Kylian Mbappé",side:"home",type:"goal"}]},
        {date:"06-16", home:"이라크", away:"노르웨이", homeScore:1, awayScore:4, status:"FT",
          goals:[{minute:29,player:"Erling Haaland",side:"away",type:"goal"},
                 {minute:39,player:"Aymen Hussein",side:"home",type:"goal"},
                 {minute:43,player:"Erling Haaland",side:"away",type:"goal"},
                 {minute:76,player:"Leo Østigård",side:"away",type:"goal"},
                 {minute:"90+6",player:"Aymen Hussein",side:"away",type:"own"}]},
        {date:"06-22", home:"프랑스", away:"이라크", homeScore:3, awayScore:0, status:"FT",
          goals:[{minute:14,player:"Kylian Mbappé",side:"home",type:"goal"},
                 {minute:54,player:"Kylian Mbappé",side:"home",type:"goal"},
                 {minute:66,player:"Ousmane Dembélé",side:"home",type:"goal"}]},
        {date:"06-22", home:"노르웨이", away:"세네갈", homeScore:3, awayScore:2, status:"FT",
          goals:[{minute:43,player:"Marcus Holmgren Pedersen",side:"home",type:"goal"},
                 {minute:48,player:"Erling Haaland",side:"home",type:"goal"},
                 {minute:53,player:"Ismaïla Sarr",side:"away",type:"goal"},
                 {minute:58,player:"Erling Haaland",side:"home",type:"goal"},
                 {minute:"90+3",player:"Ismaïla Sarr",side:"away",type:"goal"}]},
        {date:"06-26", home:"노르웨이", away:"프랑스", homeScore:1, awayScore:4, status:"FT",
          goals:[{minute:7,player:"Ousmane Dembélé",side:"away",type:"goal"},
                 {minute:20,player:"Ousmane Dembélé",side:"away",type:"goal"},
                 {minute:21,player:"Thelo Aasgaard",side:"home",type:"goal"},
                 {minute:32,player:"Ousmane Dembélé",side:"away",type:"goal"},
                 {minute:"90+4",player:"Désiré Doué",side:"away",type:"goal"}]},
        {date:"06-26", home:"세네갈", away:"이라크", homeScore:5, awayScore:0, status:"FT",
          goals:[{minute:4,player:"Habib Diarra",side:"home",type:"goal"},
                 {minute:56,player:"Ismaïla Sarr",side:"home",type:"goal"},
                 {minute:59,player:"Pape Gueye",side:"home",type:"goal"},
                 {minute:71,player:"Pape Gueye",side:"home",type:"goal"},
                 {minute:82,player:"Iliman Ndiaye",side:"home",type:"goal"}]}
      ]},

    { name:"J",
      standings:[
        {rank:1, team:"아르헨티나", played:3, won:3, drawn:0, lost:0, gf:8, ga:1, gd:7,  points:9},
        {rank:2, team:"오스트리아", played:3, won:1, drawn:1, lost:1, gf:6, ga:6, gd:0,  points:4},
        {rank:3, team:"알제리", played:3, won:1, drawn:1, lost:1, gf:5, ga:7, gd:-2, points:4},
        {rank:4, team:"요르단", played:3, won:0, drawn:0, lost:3, gf:3, ga:8, gd:-5, points:0}
      ],
      matches:[
        {date:"06-16", home:"아르헨티나", away:"알제리", homeScore:3, awayScore:0, status:"FT",
          goals:[{minute:17,player:"Messi",side:"home",type:"goal"},
                 {minute:60,player:"Messi",side:"home",type:"goal"},
                 {minute:76,player:"Messi",side:"home",type:"goal"}]},
        {date:"06-16", home:"오스트리아", away:"요르단", homeScore:3, awayScore:1, status:"FT",
          goals:[{minute:20,player:"Schmid",side:"home",type:"goal"},
                 {minute:50,player:"Olwan",side:"away",type:"goal"},
                 {minute:76,player:"Al-Arab",side:"home",type:"own"},
                 {minute:"90+12",player:"Arnautović",side:"home",type:"penalty"}]},
        {date:"06-22", home:"아르헨티나", away:"오스트리아", homeScore:2, awayScore:0, status:"FT",
          goals:[{minute:38,player:"Messi",side:"home",type:"goal"},
                 {minute:"90+5",player:"Messi",side:"home",type:"goal"}]},
        {date:"06-22", home:"요르단", away:"알제리", homeScore:1, awayScore:2, status:"FT",
          goals:[{minute:36,player:"Al-Rashdan",side:"home",type:"goal"},
                 {minute:69,player:"Benbouali",side:"away",type:"goal"},
                 {minute:82,player:"Gouiri",side:"away",type:"goal"}]},
        {date:"06-27", home:"알제리", away:"오스트리아", homeScore:3, awayScore:3, status:"FT",
          goals:[{minute:28,player:"Arnautović",side:"away",type:"goal"},
                 {minute:45,player:"Belghali",side:"home",type:"goal"},
                 {minute:55,player:"Sabitzer",side:"away",type:"goal"},
                 {minute:60,player:"Mahrez",side:"home",type:"goal"},
                 {minute:"90+3",player:"Mahrez",side:"home",type:"goal"},
                 {minute:"90+6",player:"Kalajdžić",side:"away",type:"goal"}]},
        {date:"06-27", home:"요르단", away:"아르헨티나", homeScore:1, awayScore:3, status:"FT",
          goals:[{minute:19,player:"Lo Celso",side:"away",type:"goal"},
                 {minute:31,player:"L. Martínez",side:"away",type:"penalty"},
                 {minute:55,player:"Al-Taamari",side:"home",type:"goal"},
                 {minute:80,player:"Messi",side:"away",type:"goal"}]}
      ]},

    { name:"K",
      standings:[
        {rank:1, team:"콜롬비아", played:3, won:2, drawn:1, lost:0, gf:4, ga:1, gd:3,  points:7},
        {rank:2, team:"포르투갈", played:3, won:1, drawn:2, lost:0, gf:6, ga:1, gd:5,  points:5},
        {rank:3, team:"DR콩고", played:3, won:1, drawn:1, lost:1, gf:4, ga:3, gd:1,  points:4},
        {rank:4, team:"우즈베키스탄", played:3, won:0, drawn:0, lost:3, gf:2, ga:11, gd:-9, points:0}
      ],
      matches:[
        {date:"06-17", home:"포르투갈", away:"DR콩고", homeScore:1, awayScore:1, status:"FT",
          goals:[{minute:6,player:"Neves",side:"home",type:"goal"},
                 {minute:"45+5",player:"Wissa",side:"away",type:"goal"}]},
        {date:"06-17", home:"우즈베키스탄", away:"콜롬비아", homeScore:1, awayScore:3, status:"FT",
          goals:[{minute:40,player:"Muñoz",side:"away",type:"goal"},
                 {minute:60,player:"Fayzullaev",side:"home",type:"goal"},
                 {minute:65,player:"Díaz",side:"away",type:"goal"},
                 {minute:"90+9",player:"Campaz",side:"away",type:"goal"}]},
        {date:"06-23", home:"포르투갈", away:"우즈베키스탄", homeScore:5, awayScore:0, status:"FT",
          goals:[{minute:6,player:"Ronaldo",side:"home",type:"goal"},
                 {minute:17,player:"Mendes",side:"home",type:"goal"},
                 {minute:39,player:"Ronaldo",side:"home",type:"goal"},
                 {minute:60,player:"Nematov",side:"home",type:"own"},
                 {minute:87,player:"Leão",side:"home",type:"goal"}]},
        {date:"06-23", home:"콜롬비아", away:"DR콩고", homeScore:1, awayScore:0, status:"FT",
          goals:[{minute:76,player:"Muñoz",side:"home",type:"goal"}]},
        {date:"06-27", home:"콜롬비아", away:"포르투갈", homeScore:0, awayScore:0, status:"FT", goals:[]},
        {date:"06-27", home:"DR콩고", away:"우즈베키스탄", homeScore:3, awayScore:1, status:"FT",
          goals:[{minute:10,player:"Shomurodov",side:"away",type:"goal"},
                 {minute:68,player:"Wissa",side:"home",type:"penalty"},
                 {minute:78,player:"Mayele",side:"home",type:"goal"},
                 {minute:"90+1",player:"Wissa",side:"home",type:"goal"}]}
      ]},

    { name:"L",
      standings:[
        {rank:1, team:"잉글랜드", played:3, won:2, drawn:1, lost:0, gf:6, ga:2, gd:4,  points:7},
        {rank:2, team:"크로아티아", played:3, won:2, drawn:0, lost:1, gf:5, ga:5, gd:0,  points:6},
        {rank:3, team:"가나",   played:3, won:1, drawn:1, lost:1, gf:2, ga:2, gd:0,  points:4},
        {rank:4, team:"파나마", played:3, won:0, drawn:0, lost:3, gf:0, ga:4, gd:-4, points:0}
      ],
      matches:[
        {date:"06-17", home:"잉글랜드", away:"크로아티아", homeScore:4, awayScore:2, status:"FT",
          goals:[{minute:12,player:"Harry Kane",side:"home",type:"penalty"},
                 {minute:36,player:"Martin Baturina",side:"away",type:"goal"},
                 {minute:42,player:"Harry Kane",side:"home",type:"goal"},
                 {minute:"45+5",player:"Petar Musa",side:"away",type:"goal"},
                 {minute:47,player:"Jude Bellingham",side:"home",type:"goal"},
                 {minute:85,player:"Marcus Rashford",side:"home",type:"goal"}]},
        {date:"06-17", home:"가나", away:"파나마", homeScore:1, awayScore:0, status:"FT",
          goals:[{minute:"90+5",player:"Yirenkyi",side:"home",type:"goal"}]},
        {date:"06-23", home:"잉글랜드", away:"가나", homeScore:0, awayScore:0, status:"FT", goals:[]},
        {date:"06-23", home:"파나마", away:"크로아티아", homeScore:0, awayScore:1, status:"FT",
          goals:[{minute:54,player:"Ante Budimir",side:"away",type:"goal"}]},
        {date:"06-27", home:"파나마", away:"잉글랜드", homeScore:0, awayScore:2, status:"FT",
          goals:[{minute:62,player:"Jude Bellingham",side:"away",type:"goal"},
                 {minute:67,player:"Harry Kane",side:"away",type:"goal"}]},
        {date:"06-27", home:"크로아티아", away:"가나", homeScore:2, awayScore:1, status:"FT",
          goals:[{minute:31,player:"Sučić",side:"home",type:"goal"},
                 {minute:73,player:"Luckassen",side:"away",type:"goal"},
                 {minute:83,player:"Nikola Vlašić",side:"home",type:"goal"}]}
      ]}
  ],

  // 녹아웃: 32강 종료 / 16강 진행 중(7/5 기준 2경기 완료 + 1경기 LIVE) / 8강 이후 미개최
  knockout: {
    r32:[
      {id:1,  date:"06-28", home:"남아프리카공화국", away:"캐나다", homeScore:0, awayScore:1, status:"FT", winner:"캐나다", goals:[]},
      {id:2,  date:"06-29", home:"네덜란드", away:"모로코", homeScore:1, awayScore:1, status:"FT", winner:"모로코", detail:"승부차기 3-2", goals:[]},
      {id:3,  date:"06-29", home:"독일", away:"파라과이", homeScore:1, awayScore:1, status:"FT", winner:"파라과이", detail:"승부차기 4-3", goals:[]},
      {id:4,  date:"06-30", home:"프랑스", away:"스웨덴", homeScore:3, awayScore:0, status:"FT", winner:"프랑스", goals:[]},
      {id:5,  date:"06-30", home:"코트디부아르", away:"노르웨이", homeScore:1, awayScore:2, status:"FT", winner:"노르웨이",
        goals:[{minute:39,player:"Antonio Nusa",side:"away",type:"goal"},
               {minute:74,player:"Amad Diallo",side:"home",type:"goal"},
               {minute:86,player:"Erling Haaland",side:"away",type:"goal"}]},
      {id:6,  date:"06-29", home:"브라질", away:"일본", homeScore:2, awayScore:1, status:"FT", winner:"브라질", goals:[]},
      {id:7,  date:"07-01", home:"멕시코", away:"에콰도르", homeScore:2, awayScore:0, status:"FT", winner:"멕시코", goals:[]},
      {id:8,  date:"07-01", home:"잉글랜드", away:"DR콩고", homeScore:2, awayScore:1, status:"FT", winner:"잉글랜드",
        goals:[{minute:7,player:"Brian Cipenga",side:"away",type:"goal"},
               {minute:75,player:"Harry Kane",side:"home",type:"goal"},
               {minute:86,player:"Harry Kane",side:"home",type:"goal"}]},

      {id:9,  date:"07-02", home:"포르투갈", away:"크로아티아", homeScore:2, awayScore:1, status:"FT", winner:"포르투갈", goals:[]},
      {id:10, date:"07-02", home:"스페인", away:"오스트리아", homeScore:3, awayScore:0, status:"FT", winner:"스페인", goals:[]},
      {id:11, date:"07-01", home:"미국", away:"보스니아헤르체고비나", homeScore:2, awayScore:0, status:"FT", winner:"미국", goals:[]},
      {id:12, date:"06-30", home:"벨기에", away:"세네갈", homeScore:3, awayScore:2, status:"FT", winner:"벨기에", detail:"연장 승부", goals:[]},
      {id:13, date:"07-03", home:"아르헨티나", away:"카보베르데", homeScore:3, awayScore:2, status:"FT", winner:"아르헨티나", detail:"연장 승부", goals:[]},
      {id:14, date:"07-02", home:"호주", away:"이집트", homeScore:1, awayScore:1, status:"FT", winner:"이집트", detail:"승부차기 4-2", goals:[]},
      {id:15, date:"07-02", home:"스위스", away:"알제리", homeScore:2, awayScore:0, status:"FT", winner:"스위스", goals:[]},
      {id:16, date:"07-03", home:"콜롬비아", away:"가나", homeScore:1, awayScore:0, status:"FT", winner:"콜롬비아", goals:[]}
    ],

    r16:[
      {id:101, date:"07-04", home:"캐나다", away:"모로코", homeScore:0, awayScore:3, status:"FT", winner:"모로코",
        goals:[{minute:50,player:"Azzedine Ounahi",side:"away",type:"goal"},
               {minute:82,player:"Azzedine Ounahi",side:"away",type:"goal"},
               {minute:90,player:"Soufiane Rahimi",side:"away",type:"goal"}]},
      {id:102, date:"07-04", home:"파라과이", away:"프랑스", homeScore:0, awayScore:1, status:"FT", winner:"프랑스",
        goals:[{minute:70,player:"Kylian Mbappé",side:"away",type:"penalty"}]},
      {id:103, date:"07-05", home:"브라질", away:"노르웨이", homeScore:1, awayScore:2, status:"FT", winner:"노르웨이",
        goals:[{minute:79,player:"Erling Haaland",side:"away",type:"goal"},
               {minute:90,player:"Erling Haaland",side:"away",type:"goal"},
               {minute:"90+10",player:"Neymar",side:"home",type:"penalty"}]},
      {id:104, date:"07-05", home:"멕시코", away:"잉글랜드", homeScore:2, awayScore:3, status:"FT", winner:"잉글랜드",
        goals:[{minute:36,player:"Jude Bellingham",side:"away",type:"goal"},
               {minute:38,player:"Jude Bellingham",side:"away",type:"goal"},
               {minute:42,player:"Julián Quiñones",side:"home",type:"goal"},
               {minute:60,player:"Harry Kane",side:"away",type:"penalty"},
               {minute:69,player:"Raúl Jiménez",side:"home",type:"penalty"}]},
      {id:105, date:"07-06", home:"포르투갈", away:"스페인", homeScore:null, awayScore:null, status:"NS", winner:null, goals:[]},
      {id:106, date:"07-06", home:"미국", away:"벨기에", homeScore:null, awayScore:null, status:"NS", winner:null, goals:[]},
      {id:107, date:"07-07", home:"아르헨티나", away:"이집트", homeScore:null, awayScore:null, status:"NS", winner:null, goals:[]},
      {id:108, date:"07-07", home:"스위스", away:"콜롬비아", homeScore:null, awayScore:null, status:"NS", winner:null, goals:[]}
    ],

    qf:[
      {id:201, date:"07-09", home:"프랑스", away:"모로코", homeScore:null, awayScore:null, status:"NS", winner:null, goals:[]},
      {id:202, date:"07-10", home:"노르웨이", away:"잉글랜드", homeScore:null, awayScore:null, status:"NS", winner:null, goals:[]},
      {id:203, date:"07-10", home:"미정", away:"미정", homeScore:null, awayScore:null, status:"TBD", winner:null, goals:[]},
      {id:204, date:"07-11", home:"미정", away:"미정", homeScore:null, awayScore:null, status:"TBD", winner:null, goals:[]}
    ],

    sf:[
      {id:301, date:"07-14", home:"미정", away:"미정", homeScore:null, awayScore:null, status:"TBD", winner:null, goals:[]},
      {id:302, date:"07-15", home:"미정", away:"미정", homeScore:null, awayScore:null, status:"TBD", winner:null, goals:[]}
    ],

    final:{id:401, date:"07-19", home:"미정", away:"미정", homeScore:null, awayScore:null, status:"TBD", winner:null, goals:[]}
  }
};
